import React from 'react';
import { Table } from 'react-bootstrap';

const tabelaHorario = () => (
  <Table responsive hover>
    <thead>
      <tr>
        <th></th>
        <th>Segunda</th>
        <th>Terça</th>
        <th>Quarta</th>
        <th>Quinta</th>
        <th>Sexta</th>
        <th>Sábado</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>7:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
      </tr>
      <tr>
        <td>8:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
      </tr>
      <tr>
        <td>9:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
      </tr>
      <tr>
        <td>10:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
      </tr>
      <tr>
        <td>11:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
      </tr>
      <tr>
        <td>12:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
      </tr>
      <tr>
        <td>13:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
      </tr>
      <tr>
        <td>14:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
      </tr>
      <tr>
        <td>15:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
      </tr>
      <tr>
        <td>16:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
      </tr>
      <tr>
        <td>17:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
      </tr>
      <tr>
        <td>18:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
      </tr>
      <tr>
        <td>19:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
      </tr>
      <tr>
        <td>20:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
      </tr>
      <tr>
        <td>21:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
      </tr>
    </tbody>
  </Table>
);

export default tabelaHorario;