import React from 'react';
import { Table } from 'react-bootstrap';

const timetable = () => (
  <Table responsive hover>
    <thead>
      <tr>
        <th></th>
        <th>Segunda</th>
        <th>Terça</th>
        <th>Quarta</th>
        <th>Quinta</th>
        <th>Sexta</th>
        <th>Sábado</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>6:00</td>
        <td><i>Iniciantes<sup>*</sup></i></td>
        <td>CrossFit</td>
        <td><i>Iniciantes<sup>*</sup></i></td>
        <td>CrossFit</td>
        <td><i>Iniciantes<sup>*</sup></i></td>
        <td></td>
      </tr>
      <tr>
        <td>7:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td></td>
      </tr>
      <tr>
        <td>8:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td></td>
      </tr>
      <tr>
        <td>9:00</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>CrossFit</td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>12:30</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>18:00</td>
        <td>CrossFit</td>
        <td><i>Iniciantes<sup>*</sup></i></td>
        <td>CrossFit</td>
        <td><i>Iniciantes<sup>*</sup></i></td>
        <td><i>Iniciantes<sup>*</sup></i></td>
        <td></td>
      </tr>
      <tr>
        <td>19:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td></td>
      </tr>
      <tr>
        <td>20:00</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td>CrossFit</td>
        <td></td>
      </tr>
    </tbody>
  </Table>
);

export default timetable;
